#pragma once
// ============================================================
//  Teensy_lib/src/BotConnect.h
//  BL-compatible library for Teensy 4.0
//  Handles UART bridge communication with ESP_Satellite
// ============================================================

#include <Arduino.h>
#include <Wire.h>

// ── Command constants ─────────────────────────────────────────
// These match the command strings generated by CommandParser
#define CMD_CAL_IR_MAX    "CAL_IR_MAX"
#define CMD_CAL_IR_MIN    "CAL_IR_MIN"
#define CMD_CAL_LINE_MAX  "CAL_LINE_MAX"
#define CMD_CAL_LINE_MIN  "CAL_LINE_MIN"
#define CMD_CAL_BNO       "CAL_BNO"

// ── Telemetry value types ─────────────────────────────────────
#define TELEM_INT    0
#define TELEM_FLOAT  1
#define TELEM_BOOL   2
#define TELEM_STRING 3

// ── P2P callback signature ────────────────────────────────────
typedef void (*OnP2PCb)(const char *message);

class BotConnect {
public:
    // ── State variables – updated by process() ───────────────
    // Active mode: the last selected mode is true, all others false.
    // Default at startup: mode1=true (channel 1 as standard active mode).
    bool mode1 = true;
    bool mode2 = false;
    bool mode3 = false;
    bool mode4 = false;
    bool mode5 = false;

    // Active calibration: the last received calibration command is true,
    // all others false. Default at startup: calIrMax=true (channel 1 as standard).
    bool calIrMax   = true;
    bool calIrMin   = false;
    bool calLineMax = false;
    bool calLineMin = false;
    bool calBno     = false;

    // Control active: true while a control command was received within the
    // last 500 ms, false otherwise.
    bool controlActive = false;

    // Last received control values (valid when controlActive is true).
    int16_t speed    = 0;
    int16_t angle    = 0;
    uint8_t switches = 0;
    uint8_t buttons  = 0;
    uint8_t start    = 0;
    bool led1 = false;
    bool led2 = false;
    bool led3 = false;
    bool led4 = false;

    // ── Initialisation ─────────────────────────────────────────
    // serial: the HardwareSerial connected to the ESP satellite
    // satId:  1 or 2 – determines DBG prefix (DBG1: or DBG2:)
    void begin(HardwareSerial &serial, uint8_t satId = 1);

    // ── Main loop – must be called in loop() ──────────────────
    // Updates state variables and manages the controlActive timeout.
    void process();

    // ── P2P callback (optional) ───────────────────────────────
    void onP2P(OnP2PCb cb) { _onP2P = cb; }

    // ── Telemetry helpers ─────────────────────────────────────
    // Send a named integer stream value
    void sendTelemetryInt(const char *name, int32_t value);
    // Send a named float stream value
    void sendTelemetryFloat(const char *name, float value);
    // Send a named bool stream value
    void sendTelemetryBool(const char *name, bool value);
    // Send a named string stream value
    void sendTelemetryString(const char *name, const char *value);
    // Send all LED states (Led1..Led4) as telemetry update
    void LedUpdate();

    // ── P2P communication ─────────────────────────────────────
    // Send a message to peer robot (via P2P bridge, no DBG: prefix)
    bool sendP2P(const char *message);
    // Send binary-safe payload (appends newline if not present)
    bool sendP2P(const uint8_t *data, size_t len);
    // Check if queued P2P messages are available (FIFO, ordered)
    bool hasP2P() const { return _p2pCount > 0; }
    // Pop next P2P message into buffer (null-terminated)
    bool readP2P(char *out, size_t maxLen);
    // Pop next P2P message into Arduino String
    bool readP2P(String &out);

    // ── ACK generation ────────────────────────────────────────
    // Send positive ACK for last received command (auto-called internally)
    void sendAck(uint8_t seq, uint8_t status = 0);

    // ── Debug output ──────────────────────────────────────────
    void setDebugEnabled(bool en) { _debugEnabled = en; }

private:
    HardwareSerial *_serial = nullptr;
    uint8_t         _satId  = 1;
    bool            _debugEnabled = true;

    char    _rxBuf[512];
    int     _rxIdx = 0;
    static const size_t P2P_MAX_MSG_LEN = 256;
    static const uint8_t P2P_QUEUE_SIZE = 8;
    char    _p2pQueue[P2P_QUEUE_SIZE][P2P_MAX_MSG_LEN];
    uint8_t _p2pHead = 0;
    uint8_t _p2pCount = 0;

    // Timestamp of the last received control command (ms)
    uint32_t _lastCtrlMs = 0;
    bool     _ctrlReceived = false;  // guard: ignore millis() wrap at startup

    OnP2PCb _onP2P = nullptr;

    void _parseLine(const char *line);
    void _sendLine(const char *line);
    void _enqueueP2P(const char *line);
};

class BotConnect_i2C {
public:
    bool mode1 = true;
    bool mode2 = false;
    bool mode3 = false;
    bool mode4 = false;
    bool mode5 = false;

    bool calIrMax   = true;
    bool calIrMin   = false;
    bool calLineMax = false;
    bool calLineMin = false;
    bool calBno     = false;

    bool controlActive = false;

    int16_t speed    = 0;
    int16_t angle    = 0;
    uint8_t switches = 0;
    uint8_t buttons  = 0;
    uint8_t start    = 0;
    bool led1 = false;
    bool led2 = false;
    bool led3 = false;
    bool led4 = false;

    void begin(TwoWire &wire = Wire, uint8_t address = 0x03);
    void process();

    void sendTelemetryInt(const char *name, int32_t value);
    void sendTelemetryFloat(const char *name, float value);
    void sendTelemetryBool(const char *name, bool value);
    void sendTelemetryString(const char *name, const char *value);
    void LedUpdate();

private:
    TwoWire *_wire = nullptr;
    uint8_t  _address = 0x03;
    char     _rxBuf[128];
    bool     _ctrlReceived = false;
    uint32_t _lastCtrlMs = 0;

    void _parseLine(const char *line);
    void _sendLine(const char *line);
};

// Global instance (compatible with BL.h usage pattern)
extern BotConnect BC;
extern BotConnect_i2C BC_I2C;
