name: Trigger GitLab Sync

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Sync Pipeline
        run: |
          curl -X POST \
            --fail \
            -F token= glptt-r1oyQkQgJWoU_HTBV7uR \
            -F ref=master \
            https://git.markdorf-robotics.de/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
